[package]
name = "alliot"
version = "0.1.0"
description = "Приложение Alliot"
authors = ["you"]
edition = "2021"
default-run = "alliot"

[lib]
name = "alliot_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "unstable"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
whisper-rs = { version = "0.16.0", features = ["log_backend", "cuda"] }
cpal = "0.15"
